### ISSUE TITLE
INSTALACAO - Atualizar README.md

### ISSUE THREAD

**Issue by future2back** [cleitonleonel/redecanais#1]
Fala @cleitonleonel , tudo bem? Voce poderia por favor atualizar o README.md explicando como faz para instalar o projeto?
Tentei utilizar:
`python redecanais.py --search hbo`
dentro da pasta redecanais e retorna:
`Sistema Operacional win suportado!!!`

Se puder atualizar o readme com o setup e utilizacao vai ser otimo.

Abracos!

**Comment by cleitonleonel** [comment]
@future2back Boas amigo(a), vou atualizar o readme em breve...mas vc pode instalar o projeto utilizando o pacote que está no pypi com um simples ```pip install redecanais``` ...
